# Fundamentals :

https://www.learnpytorch.io/00_pytorch_fundamentals/

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)


2.1.0+cu121


## Scalar :

In [1]:
# Scalar :
scalar=torch.tensor(7)
print(scalar)

# Attributes of scalar :
print(scalar.ndim) # Dim
print(scalar.item()) # Value

NameError: name 'torch' is not defined

## Vector :

In [ ]:
# Vector :
vector=torch.tensor([7,1])
print(vector)

#Attributes of a vector :
print(vector.ndim) # nb de crochets fermés
print(vector.shape) # nb d'elem

torch.Size([2])

## Matrix :

In [ ]:
# Matrix :
matrix= torch.tensor([[7,7],[7,7]])
print(matrix)

# Atributes of a matrix :
print(matrix.ndim)
print(matrix[1,1]) # accès aux values
print(matrix.shape)

tensor([[7, 7],
        [7, 7]])
2
tensor(7)
torch.Size([2, 2])


## Tensor :

In [ ]:
# Tensor :
TENSOR=torch.tensor([[[1,2,3],
                      [4,5,6],
                      [7,8,9]]])
print(TENSOR)

# Attributes :
print(TENSOR.ndim)
print(TENSOR.shape) # first bracket, second, third en partant de l'exterieur
print(TENSOR[0])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
3
torch.Size([1, 3, 3])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [ ]:
## Random tensor :

random=torch.rand(3,4) # size a l'interieur

print(random)

print(random.ndim)


tensor([[0.2687, 0.5223, 0.7642, 0.3856],
        [0.7961, 0.9938, 0.5101, 0.6752],
        [0.0628, 0.0202, 0.7120, 0.3083]])
2


In [ ]:
# Exemple d'une image
random_image=torch.rand(size=(224,224,3)) # height, width, colour channel

print(random_image.shape, random_image.ndim)

torch.Size([224, 224, 3]) 3


## Special tensors :

In [ ]:
zeros=torch.zeros((3,4))
print(zeros)

ones=torch.ones((3,4))
print(ones)

print(zeros.dtype, ones.dtype)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
torch.float32 torch.float32


In [ ]:
# Range of tensor :
print(torch.range(start=0,end=10)) # start : end included; depreciated => use arange

one_to_ten=torch.arange(start=0,end=10,step=1)
print(torch.arange(start=0,end=10,step=0.5)) #

# tensors of same shape as input
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

ten_ones=torch.ones_like(input=one_to_ten)
ten_ones

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000,
        4.5000, 5.0000, 5.5000, 6.0000, 6.5000, 7.0000, 7.5000, 8.0000, 8.5000,
        9.0000, 9.5000])


<ipython-input-51-02e36782be3f>:3: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  print(torch.range(start=0,end=10)) # start : end included; depreciated => use arange


tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

## Datatypes :

In [ ]:
float_32_tensor= torch.tensor([3.0,6.0,9.0],
                              dtype=None,
                              device=None,
                              requires_grad=False)
print(float_32_tensor,float_32_tensor.dtype)

# 3 errors : tensors datatypes; tensors shape; tensors not on the same device (cpu/cuda)

float_16_tensor=float_32_tensor.type(torch.float16)
print(float_16_tensor,float_16_tensor.dtype)

tensor([3., 6., 9.]) torch.float32
tensor([3., 6., 9.], dtype=torch.float16) torch.float16


## Manipulating tensors :

In [ ]:
# Getting info from tensors :

print(f"datatype : {float_32_tensor.dtype}") #datatype

print(float_32_tensor.shape) # shape

print(float_32_tensor.device) # which device

# diff btw shape and size : size est une fonc donc tensor.size() et tensor.shape (car shape est attribute)

datatype : torch.float32
torch.Size([3])
cpu


### Opérations :

In [ ]:
%%time
tensor=torch.tensor([1,2,3])

print(tensor+3)

print(tensor-3)

print(tensor*10)

print(tensor) # Didn't change

print(tensor/10)

#matrice :
mat1=torch.tensor([[1,2,3],
                   [1,2,3],
                   [1,2,3]])
print(mat1)

mat2=mat1*3+5

print(mat2)

print(mat1*mat2) #Element wise

print(torch.matmul(mat1,mat2)) #dot product (produit matriciel)
print(torch.mm(mat1,mat2)) #juste un alias de matmul

tensor([4, 5, 6])
tensor([-2, -1,  0])
tensor([10, 20, 30])
tensor([1, 2, 3])
tensor([0.1000, 0.2000, 0.3000])
tensor([[1, 2, 3],
        [1, 2, 3],
        [1, 2, 3]])
tensor([[ 8, 11, 14],
        [ 8, 11, 14],
        [ 8, 11, 14]])
tensor([[ 8, 22, 42],
        [ 8, 22, 42],
        [ 8, 22, 42]])
tensor([[48, 66, 84],
        [48, 66, 84],
        [48, 66, 84]])
tensor([[48, 66, 84],
        [48, 66, 84],
        [48, 66, 84]])
CPU times: user 8.82 ms, sys: 970 µs, total: 9.79 ms
Wall time: 12 ms


In [ ]:
#Transposee :
mat1.T

tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3]])

### Min, Max, Mean, Argmin, Argmax :

In [3]:
tens=  torch.arange(0,100,10)
tens

NameError: name 'torch' is not defined

In [5]:
torch.min(tens), tens.min()

torch.max(tens), tens.max()

NameError: name 'torch' is not defined

In [ ]:
torch.mean(tens.type(torch.float32)), tens.type(torch.float32).mean()

# mean a besoin d'un float32 pour fonctionner

(tensor(45.), tensor(45.))

In [ ]:
torch.sum(tens), tens.sum()

(tensor(450), tensor(450))

In [ ]:
torch.argmin(tens), tens.argmin()

torch.argmax(tens), tens.argmax()

(tensor(9), tensor(9))

### Reshaping, view, stack, (un)squeeze, permute :  

In [ ]:
## reshaping, stacking and squeeze/unsqueeze

## view : return a view of an imput tensor of certain shape but keep the same memory

## stacking : combine multiple tensors on top of each other or side by side

## squeeze : removes all "1" dim from tensor

## unsqueeze : add a "1" dim to a target tensor

## permute : return a view of the input with dimensions permuted in a certian way

In [ ]:
x= torch.arange(1.,10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# reshape
x.reshaped=x.reshape(1,9)
x.reshaped, x.reshaped.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# view :
z=x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
# changing z changes x bc view shares the same memory
z[:,0]=5
x,z

(tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]),
 tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]))

In [ ]:
# stack

x_stacked=torch.stack([x,x,x,x],dim=0)
x_stacked,x_stacked.shape

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.],
         [5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([4, 9]))

In [ ]:
# squeeze and unsqueeze

x.reshaped.shape, x.reshaped.squeeze(), x.reshaped.squeeze().shape

x_squeeze=x.reshaped.squeeze()

x_squeeze.shape, x_squeeze.unsqueeze(dim=1), x_squeeze.unsqueeze(dim=1).shape

(torch.Size([9]),
 tensor([[5.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [ ]:
# permute :
x_orig=torch.rand(size=(224,224,3))

x_permuted=x_orig.permute(2,0,1) # permute est une view !!!
x_orig.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

### Indexing :

In [6]:
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

NameError: name 'torch' is not defined

In [ ]:
x[0], x[0][0], x[0][0][0]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]),
 tensor(1))

In [ ]:
x[0][2][2]
x[0,:,2]

tensor(9)

## PyTorch tensor & numpy :

In [ ]:
## numpy array to tensor
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array, tensor # default type of array is float64

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array=array+1
array, tensor # doesn't change

(array([3., 4., 5., 6., 7., 8., 9.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
# tensor to numpy array

tensor= torch.ones(7)
numpy_tensor=tensor.numpy()

tensor, numpy_tensor # keep the datatype of float32 from torch !!

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tensor=tensor+1
tensor,numpy_tensor # doesn't change

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducability :

In [ ]:
x=torch.rand(3,4)
y=torch.rand(3,4)
x,y,x==y

(tensor([[0.1097, 0.7128, 0.1859, 0.6239],
         [0.8706, 0.2349, 0.5377, 0.3719],
         [0.3510, 0.4692, 0.2522, 0.9966]]),
 tensor([[0.0313, 0.9332, 0.6380, 0.5432],
         [0.5281, 0.4906, 0.7644, 0.1988],
         [0.2425, 0.8104, 0.8355, 0.4865]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [ ]:
# fix the seed

torch.manual_seed(42)
z=torch.rand(3,4)

torch.manual_seed(42) # only apply to one line of random code !!!!
z2=torch.rand(3,4)

z,z2,z==z2

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

## Cuda & PyTorch :

In [ ]:
# get GPU : collab, get your own or cloud computing (gcp, aws, azure)
!nvidia-smi

(device(type='cpu'), device(type='cuda', index=0))

In [ ]:
torch.cuda.is_available()

True

In [ ]:
device="cuda" if torch.cuda.is_available() else "cpu"
print(device)

"""
if torch.cuda.is_available()==True :
  device="cuda"
else : device="cpu"
"""

torch.cuda.device_count()

cuda


1

In [ ]:
x_cpu=torch.rand(3,3,device="cpu")
x_gpu=torch.rand(3,3,device="cuda")

x_cpu.device,x_gpu.device

(device(type='cpu'), device(type='cuda', index=0))

In [ ]:
# move to gpu :

tensor_gpu=tensor.to(device) # from gpu to cpu and cpu to gpu the method work
tensor_gpu

tensor([2., 2., 2., 2., 2., 2., 2.], device='cuda:0')

In [ ]:
# can't transform a tensor on gpu to numpy !! !! !! !
#tensor_gpu.numpy() #error !
tensor_gpu.cpu().numpy(), tensor_gpu.to("cpu").numpy()

(array([2., 2., 2., 2., 2., 2., 2.], dtype=float32),
 array([2., 2., 2., 2., 2., 2., 2.], dtype=float32))

In [ ]:
# go back to cpu
tensor_gpu.cpu(), tensor_gpu.to("cpu")

(tensor([2., 2., 2., 2., 2., 2., 2.]), tensor([2., 2., 2., 2., 2., 2., 2.]))

# Exercices !

https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises

In [ ]:
x=torch.rand(7,7)
y=torch.rand(1,7)

z=torch.matmul(x,y.T)
x,y,z

(tensor([[0.6115, 0.2234, 0.2469, 0.4761, 0.7792, 0.3722, 0.2147],
         [0.3288, 0.1265, 0.6783, 0.8870, 0.0293, 0.6161, 0.7583],
         [0.5907, 0.3219, 0.7610, 0.7628, 0.6870, 0.4121, 0.3676],
         [0.5535, 0.4117, 0.3510, 0.8196, 0.9297, 0.4505, 0.3881],
         [0.5073, 0.4701, 0.6202, 0.6401, 0.0459, 0.3155, 0.9211],
         [0.6948, 0.4751, 0.1985, 0.1941, 0.0521, 0.3370, 0.6689],
         [0.8188, 0.7308, 0.0580, 0.1993, 0.4211, 0.9837, 0.5723]]),
 tensor([[0.3705, 0.7069, 0.3096, 0.1764, 0.8649, 0.2726, 0.3998]]),
 tensor([[1.4061],
         [1.0741],
         [1.6700],
         [1.8314],
         [1.3191],
         [1.0933],
         [1.7343]]))

In [ ]:
seed=42
torch.manual_seed(seed)
x=torch.rand(7,7)
y=torch.rand(1,7)
z=torch.mm(x,y.T)

x,y,z

(tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566],
         [0.7936, 0.9408, 0.1332, 0.9346, 0.5936, 0.8694, 0.5677],
         [0.7411, 0.4294, 0.8854, 0.5739, 0.2666, 0.6274, 0.2696],
         [0.4414, 0.2969, 0.8317, 0.1053, 0.2695, 0.3588, 0.1994],
         [0.5472, 0.0062, 0.9516, 0.0753, 0.8860, 0.5832, 0.3376],
         [0.8090, 0.5779, 0.9040, 0.5547, 0.3423, 0.6343, 0.3644],
         [0.7104, 0.9464, 0.7890, 0.2814, 0.7886, 0.5895, 0.7539]]),
 tensor([[0.1952, 0.0050, 0.3068, 0.1165, 0.9103, 0.6440, 0.7071]]),
 tensor([[1.3299],
         [1.8111],
         [1.3228],
         [0.9725],
         [1.8285],
         [1.4806],
         [2.0489]]))

In [ ]:
#torch.cuda.manual_seed(1234)
torch.manual_seed(1234)
x=torch.rand(2,3)
y=torch.rand(2,3)

x_gpu=x.to("cuda")
y_gpu=y.to("cuda")

x,y

z=torch.mm(x_gpu,y_gpu.T)
z, z.max(), z.min(), z.argmax(), z.argmin()

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 tensor(0.5617, device='cuda:0'),
 tensor(0.3647, device='cuda:0'),
 tensor(3, device='cuda:0'),
 tensor(0, device='cuda:0'))

In [ ]:
torch.manual_seed(7)
x=torch.rand(1,1,1,10)
y=x.squeeze()
x,x.shape,y,y.shape

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 torch.Size([1, 1, 1, 10]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))